// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const addComment = `-- name: AddComment :one
INSERT INTO comments (body, created, id, line, path, resolved, side, slug, updated)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING body, created, id, line, path, resolved, side, slug, updated
`

type AddCommentParams struct {
	Body     string
	Created  int64
	ID       string
	Line     int64
	Path     string
	Resolved int64
	Side     string
	Slug     string
	Updated  int64
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, addComment,
		arg.Body,
		arg.Created,
		arg.ID,
		arg.Line,
		arg.Path,
		arg.Resolved,
		arg.Side,
		arg.Slug,
		arg.Updated,
	)
	var i Comment
	err := row.Scan(
		&i.Body,
		&i.Created,
		&i.ID,
		&i.Line,
		&i.Path,
		&i.Resolved,
		&i.Side,
		&i.Slug,
		&i.Updated,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments WHERE id = ? AND slug = ?
`

type DeleteCommentParams struct {
	ID   string
	Slug string
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComment, arg.ID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getComment = `-- name: GetComment :one
SELECT body, created, id, line, path, resolved, side, slug, updated FROM comments WHERE id = ? AND slug = ?
`

type GetCommentParams struct {
	ID   string
	Slug string
}

func (q *Queries) GetComment(ctx context.Context, arg GetCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, arg.ID, arg.Slug)
	var i Comment
	err := row.Scan(
		&i.Body,
		&i.Created,
		&i.ID,
		&i.Line,
		&i.Path,
		&i.Resolved,
		&i.Side,
		&i.Slug,
		&i.Updated,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT body, created, id, line, path, resolved, side, slug, updated FROM comments WHERE slug = ? ORDER BY created ASC
`

func (q *Queries) ListComments(ctx context.Context, slug string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.Body,
			&i.Created,
			&i.ID,
			&i.Line,
			&i.Path,
			&i.Resolved,
			&i.Side,
			&i.Slug,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommentResolved = `-- name: SetCommentResolved :execrows
UPDATE comments SET resolved = ?, updated = ? WHERE id = ? AND slug = ?
`

type SetCommentResolvedParams struct {
	Resolved int64
	Updated  int64
	ID       string
	Slug     string
}

func (q *Queries) SetCommentResolved(ctx context.Context, arg SetCommentResolvedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCommentResolved,
		arg.Resolved,
		arg.Updated,
		arg.ID,
		arg.Slug,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCommentBody = `-- name: UpdateCommentBody :execrows
UPDATE comments SET body = ?, updated = ? WHERE id = ? AND slug = ?
`

type UpdateCommentBodyParams struct {
	Body    string
	Updated int64
	ID      string
	Slug    string
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCommentBody,
		arg.Body,
		arg.Updated,
		arg.ID,
		arg.Slug,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
