// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Comment struct {
	Body     string
	Created  int64
	ID       string
	Line     int64
	Path     string
	Resolved int64
	Side     string
	Slug     string
	Updated  int64
}
