// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlite

import (
	"context"
)

const addComment = `-- name: AddComment :one
INSERT INTO comments (body, branch, id, line, path, side, slug)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING body, branch, created_at, id, line, path, resolved, resolved_body, side, slug, updated_at
`

type AddCommentParams struct {
	Body   string
	Branch string
	ID     string
	Line   int64
	Path   string
	Side   string
	Slug   string
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, addComment,
		arg.Body,
		arg.Branch,
		arg.ID,
		arg.Line,
		arg.Path,
		arg.Side,
		arg.Slug,
	)
	var i Comment
	err := row.Scan(
		&i.Body,
		&i.Branch,
		&i.CreatedAt,
		&i.ID,
		&i.Line,
		&i.Path,
		&i.Resolved,
		&i.ResolvedBody,
		&i.Side,
		&i.Slug,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments WHERE id = ? AND slug = ?
`

type DeleteCommentParams struct {
	ID   string
	Slug string
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComment, arg.ID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getComment = `-- name: GetComment :one
SELECT body, branch, created_at, id, line, path, resolved, resolved_body, side, slug, updated_at FROM comments WHERE id = ? AND slug = ?
`

type GetCommentParams struct {
	ID   string
	Slug string
}

func (q *Queries) GetComment(ctx context.Context, arg GetCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, arg.ID, arg.Slug)
	var i Comment
	err := row.Scan(
		&i.Body,
		&i.Branch,
		&i.CreatedAt,
		&i.ID,
		&i.Line,
		&i.Path,
		&i.Resolved,
		&i.ResolvedBody,
		&i.Side,
		&i.Slug,
		&i.UpdatedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT body, branch, created_at, id, line, path, resolved, resolved_body, side, slug, updated_at FROM comments WHERE slug = ? AND branch = ? ORDER BY created_at ASC
`

type ListCommentsParams struct {
	Slug   string
	Branch string
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, arg.Slug, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.Body,
			&i.Branch,
			&i.CreatedAt,
			&i.ID,
			&i.Line,
			&i.Path,
			&i.Resolved,
			&i.ResolvedBody,
			&i.Side,
			&i.Slug,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommentResolved = `-- name: SetCommentResolved :execrows
UPDATE comments SET resolved = ?, resolved_body = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND slug = ?
`

type SetCommentResolvedParams struct {
	Resolved     int64
	ResolvedBody string
	ID           string
	Slug         string
}

func (q *Queries) SetCommentResolved(ctx context.Context, arg SetCommentResolvedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCommentResolved,
		arg.Resolved,
		arg.ResolvedBody,
		arg.ID,
		arg.Slug,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCommentBody = `-- name: UpdateCommentBody :execrows
UPDATE comments SET body = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND slug = ?
`

type UpdateCommentBodyParams struct {
	Body string
	ID   string
	Slug string
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCommentBody, arg.Body, arg.ID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
