// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"time"
)

type Comment struct {
	Body         string
	Branch       string
	CreatedAt    time.Time
	ID           string
	Line         int64
	Path         string
	Resolved     int64
	ResolvedBody string
	Side         string
	Slug         string
	UpdatedAt    time.Time
}
